server:
  host: "https://foodsharing.de"
  login: "/api/user/login"
  dashboard: "/?page=dashboard"
  profile: "/profile/"

stores:
  fairteilers: [ 4089, 30932, 32635 ]
  exclude: [ ]#[ 32635,39290 ]